app/views/admin.py
import io
import csv
import traceback as tb
from flask import Blueprint, render_template, request, redirect, flash
from flask_login import login_required
from utils import connection, cursor

admin = Blueprint('admin', __name__, url_prefix='/admin',
                   template_folder='templates')

@admin.route("/most_borrowed", methods=["GET"]) # most borrowed books
#@login_required
def most_borrowed():
    limit = request.args.get('n', '10')
    freq_query = f"""SELECT docid, count(*) as doc_count from borrows BS
                GROUP BY docid
                ORDER BY count(*) DESC
                LIMIT {limit}"""
    docs = f"""SELECT D.docid, D.title, doc_count from document D
              JOIN ({freq_query}) as freq
              ON D.docid = freq.docid"""
    try:
        cursor.execute(docs)
    except Exception as e:
        rows=[]
        connection.rollback()
        flash(f"Unexpected error while fetching result: {e}")
        return render_template("adminResults.html", rows=rows)
    rows = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]
    rows.insert(0, columns)
    print(rows)
    return render_template('adminResults.html', rows=rows)

@admin.route("/most_popular", methods=["GET"]) # most popular books of a year
#@login_required
def most_popular():
    limit = request.args.get('n', 10)
    year = request.args.get('year')
    selected_txns = f"""SELECT BOR_NO from BORROWING where BDTIME BETWEEN 
                    to_date('{year}-01-01','YYYY-MM-DD') 
                    AND to_date('{year}-12-31','YYYY-MM-DD')"""
    freq_query = f"""SELECT BS.docid, count(*) as doc_count from borrows BS
                    JOIN ({selected_txns}) as sel
                    ON BS.bor_no = sel.bor_no 
                    GROUP BY docid
                    ORDER BY count(*) DESC
                    LIMIT {limit}"""
    docs = f"""SELECT D.docid, D.title, doc_count from document D
              JOIN ({freq_query}) as freq
              ON D.docid = freq.docid"""
    print(docs)
    try:
        cursor.execute(docs)
    except Exception as e:
        rows=[]
        connection.rollback()
        flash(f"Unexpected error while fetching result: {e}")
        return render_template("adminResults.html", rows=rows)
    rows = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]
    rows.insert(0, columns)
    print(rows)
    return render_template('adminResults.html', rows=rows)

@admin.route("/avg_fine", methods=["GET"]) # average fine paid by the borrowers by branch in a time period
#@login_required
def avg_fine():
    from_date = request.args.get('from_date', '2022-12-01')
    to_date = request.args.get('to_date', '2022-12-31')
    selected_txns = f"""SELECT BOR_NO, GREATEST(0, (date_part('day', rdtime) - date_part('day', bdtime) - 20))*0.20 as fine 
                    from BORROWING where RDTIME is not NULL and
                    BDTIME BETWEEN to_date('{from_date}','YYYY-MM-DD') 
                    AND to_date('{to_date}','YYYY-MM-DD')"""
    fines_query = f"""SELECT BID, avg(fine) as Average_Fine from BORROWS BR
                    JOIN ({selected_txns}) as sel
                    on BR.bor_no = sel.bor_no
                    GROUP BY BID
                    ORDER BY BID asc"""
    branch_query = f"""SELECT B.bid, b.lname as name, b.location as location, Average_Fine from Branch B
                    JOIN ({fines_query}) as fin
                    on B.bid = fin.bid"""
    try:
        cursor.execute(branch_query)
    except Exception as e:
        rows=[]
        connection.rollback()
        flash(f"Unexpected error while fetching result: {e}")
        return render_template("adminResults.html", rows=rows)
    rows = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]
    rows.insert(0, columns)
    print(rows)
    return render_template('adminResults.html', rows=rows)

@admin.route("/fbib", methods=["GET"]) # Get the N most frequent borrowers in branch I.
#@login_required
def most_freq_borrowers_in_branch():
    limit = request.args.get('n', '10')
    id = request.args.get('id')
    freq_query = f"""SELECT rid, count(*) as doc_count from borrows BS
                WHERE bid={id}
                GROUP BY rid
                ORDER BY count(*) DESC
                LIMIT {limit}"""
    docs = f"""SELECT R.rid, R.rname, R.rtype, R.raddress, R.phone_no, doc_count from reader R
              JOIN ({freq_query}) as freq
              ON R.rid = freq.rid"""
    try:
        cursor.execute(docs)
    except Exception as e:
        rows=[]
        connection.rollback()
        flash(f"Unexpected error while fetching result: {e}")
        return render_template("adminResults.html", rows=rows)
    rows = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]
    rows.insert(0, columns)
    print(rows)
    return render_template('adminResults.html', rows=rows)

# Get the top N most frequent borrowers in the library and the number of books borrowed.
@admin.route("/freq_borrowers", methods=["GET"])
#@login_required
def freq_borrowers():
    limit = request.args.get('n', '10')
    freq_query = f"""SELECT rid, count(*) as doc_count from borrows BS
                GROUP BY rid
                ORDER BY count(*) DESC
                LIMIT {limit}"""
    docs = f"""SELECT R.rid, R.rname, R.rtype, R.raddress, R.phone_no, doc_count from reader R
              JOIN ({freq_query}) as freq
              ON R.rid = freq.rid"""
    try:
        cursor.execute(docs)
    except Exception as e:
        rows=[]
        connection.rollback()
        flash(f"Unexpected error while fetching result: {e}")
        return render_template("adminResults.html", rows=rows)
    rows = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]
    rows.insert(0, columns)
    print(rows)
    return render_template('adminResults.html', rows=rows)

@admin.route("/mbib", methods=["GET"]) # Get the N most borrowed books in branch I.
#@login_required
def most_borrowed_in_branch():
    limit = request.args.get('n', '10')
    id = request.args.get('id')
    freq_query = f"""SELECT docid, count(*) as doc_count from borrows BS
                WHERE bid={id}
                GROUP BY docid
                ORDER BY count(*) DESC
                LIMIT {limit}"""
    docs = f"""SELECT D.docid, D.title, doc_count from document D
              JOIN ({freq_query}) as freq
              ON D.docid = freq.docid"""
    try:
        cursor.execute(docs)
    except Exception as e:
        rows=[]
        connection.rollback()
        flash(f"Unexpected error while fetching result: {e}")
        return render_template("adminResults.html", rows=rows)
    rows = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]
    rows.insert(0, columns)
    print(rows)
    return render_template('adminResults.html', rows=rows)

@admin.route("/branch", methods=["GET"]) # Print branch information (name and location). 
#@login_required
def branch():
    id = request.args.get('id')
    query = f"""Select * from Branch where bid={id};"""
    try:
        cursor.execute(query)
    except Exception as e:
        rows=[]
        connection.rollback()
        flash(f"Unexpected error while fetching result: {e}")
        return render_template("adminResults.html", rows=rows)
    rows = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]
    rows.insert(0, columns)
    print(rows)
    return render_template('adminResults.html', rows=rows)

@admin.route("/reader", methods=["POST"]) # Add new reader. 
#@login_required
def reader():
    form_data = {}
    fields = ["rtype", "rname", "raddress", "phone_no"]
    for field in fields:
        if not request.form.get(field):
            flash(f"{field} is a mandatory field", "danger")
            return render_template('adminHome.html')
        form_data[field] = request.form.get(field)
    try:
        query= f"""INSERT INTO READER({','.join(fields)}) VALUES
                        ('{form_data['rtype']}', '{form_data['rname']}', 
                         '{form_data['raddress']}','{form_data['phone_no']}') RETURNING rid;"""
                         
        print(query)
        cursor.execute(query)
        connection.commit()
        flash(f"Added New Reader, Reader id: {cursor.fetchall()[0][0]}", "success")
    except Exception as e:
        print(tb.format_exc)
        connection.rollback()
        flash(f"Unexpected error while trying to add reader: {e}", "danger")
    return render_template('adminHome.html')

@admin.route("/document", methods=["GET", "POST"]) # Search document copy and check its status.  
#@login_required
def document():
    if request.method == "GET":
        docid = request.args.get('docid')
        copyno = request.args.get('copynum')
        reserve_query = f"""SELECT docid, copyno, bid, dtime as tx_time, NULL as ret_time, 'RESERVED' as status  from RESERVES R
                            JOIN RESERVATION RI ON R.reservation_no = RI.res_no and R.docid = {docid} and R.copyno = {copyno}"""
        borrow_query = f"""SELECT docid, copyno, bid, bdtime as tx_time, rdtime as ret_time, 'BORROWED' as STATUS from BORROWS B
                          JOIN BORROWING BI ON B.bor_no = BI.bor_no and B.docid = {docid} and B.copyno = {copyno} and BI.rdtime is null"""
        docs = f"""  SELECT sub1.docid as "Doc ID", sub1.copyno as "COPY_NO", title as "Title",
                     location as "BranchLocation", tx_time as "Borrowed On", ret_time as "Returned On",
                     status from 
                    (({reserve_query}) UNION ({borrow_query})) as sub1
                    JOIN DOCUMENT D on D.docid={docid}
                    JOIN BRANCH B ON sub1.bid = B.bid
                    """
        try:
            cursor.execute(docs)
            rows = cursor.fetchall()
            if not rows:
                cursor.execute(f"""SELECT title as DOC_TITLE, copyno as COPY_NO, B.lname, NULL as tx_time,

app/templates/admin.html
{% extends "layout.html" %}
{%block content%}
<h2 class="page_title">Admin Console</h2>
<div>
    <form class="each-api">
        <div class="form-group">
            <label class="field-name" for="docIdToAdd">Document ID</label>
            <input type="documentId" class="form-control form-input" id="docIdToAdd" placeholder="Enter document ID">
        </div>
        <div class="form-group">
            <label class="field-name" for="copyNoToAdd">Copy No</label>
            <input type="copyId" class="form-control form-input" id="copyNoToAdd" placeholder="Enter Copy No">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

app/templates/adminHome.html
{% extends "adminLayout.html" %}
{%block content%}
<br>
<br>

<div style="margin-left: 40px;">
    <form method="POST" action="{{url_for('admin.document')}}"
        style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px; margin-right: 200px; padding: 10px;">
        <label style="font-size: 20px; color: white;" for="title">Add a document. </label>
        <div class="form-group" style="display: flex;">
            <input style="margin-left: 5px;" type="text" name="title" id="title" placeholder="Enter Title">
            <input style="margin-left: 5px;" type="date" name="pdate" id="pdate" placeholder="Published On">
            <input style="margin-left: 5px;" type="text" name="publisherid" id="publisherid" placeholder="Publisher ID">
            <input style="margin-left: 5px;" type="text" name="bid" id="bid" placeholder="Branch ID">
            <input style="margin-left: 5px;" type="text" name="position" id="position" placeholder="Position">
        </div>
        <div>
            <select type="text" name="doctype" id="doctype">
                <option value="book" selected>Book</option>
                <option value="journal">Journal</option>
                <option value="proceeding">Conference Proceeding</option>
            </select>
        </div>
        <div class="form-group" style="display: flexbox;">
            <label style="font-size: 20px; color: white;" for="bid">Book:</label>
            <input style="margin-left: 5px;" type="text" name="isbn" id="isbn" placeholder="Enter ISBN">
            <input style="margin-left: 5px;" type="text" name="author" id="author" placeholder="Enter Author">
        </div>
        <div class="form-group" style="display:flexbox;">
            <label style="font-size: 20px; color: white;" for="bid">Journal:</label>
            <input style="margin-left: 5px;" type="number" name="volnum" id="volnum" placeholder="Volume Num">
            <input style="margin-left: 5px;" type="text" name="meditor" id="meditor" placeholder="Main Editor">
            <input style="margin-left: 5px;" type="text" name="scope" id="scope" placeholder="Scope">

            <table id="myTable">
                <tr>
                    <td><input type="number" name="issuenum" id="issuenum" placeholder="Enter Number of Issues"></td>
                    <td><input type="textarea" name="geditors" id="geditors" placeholder="Enter Guest Editor name(s)"></td>
                </tr>
            </table>
            <br>

        </div>
        <div class="form-group" style="display: flexbox;">
            <label style="font-size: 20px; color: white;" for="bid">Proceeding:</label>
            <input style="margin-left: 5px;" type="date" name="cdate" id="cdate" placeholder="Enter Date">
            <input style="margin-left: 5px;" type="text" name="clocation" id="clocation" placeholder="Enter Location">
            <input style="margin-left: 5px;" type="text" name="ceditor" id="ceditor" placeholder="Enter Editor">

            <table id="myTable1">
                <tr>
                    <td><input type="number" name="numchair" id="numchair" placeholder="Enter Number of Chairs" /></td>
                    <td><input type="textarea" name="chairs" id="chairs" placeholder="Enter Chair(s)" /></td>
                </tr>
            </table>
            <br>

        </div>
        <div style="margin-left: auto; margin-right: auto;">
            <button type="submit" class="btn btn-primary" >Submit</button>
        </div>
    </form>
</div>
<br>
<div style="margin-left: 40px;">
    <form method="POST" action="{{url_for('admin.add_copy')}}"
        style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px; margin-right: 200px; padding: 10px;">
        <label style="font-size: 20px; color: white;" for="copynum">Add document copy. </label>
        <div class="form-group" style="display: flex;">
            <input style="margin-left: 5px;" type="number" name="docid" id="docid" placeholder="Enter DOCID">
            <input style="margin-left: 5px;" type="number" name="bid" id="bid" placeholder="Enter Branch ID">
            <input style="margin-left: 5px;" type="text" name="position" id="position" placeholder="Enter Position">
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<br>
<div style="margin-left: 40px;">
    <form method="GET" action="{{url_for('admin.document')}}"
        style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px; margin-right: 200px; padding: 10px;">
        <label style="font-size: 20px; color: white;" for="docid">Search document copy and check its status. </label>
        <div class="form-group" style="display: flex;">
            <input style="margin-left: 5px;" type="number" name="docid" id="docid" placeholder="Enter DOCID">
            <input style="margin-left: 5px;" type="number" name="copynum" id="copynum" placeholder="Enter Copy Number">
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<br>
<div style="margin-left: 40px;">
    <form method="POST" action="{{url_for('admin.reader')}}"
        style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px; margin-right: 200px; padding: 10px;">
        <label style="font-size: 20px; color: white;" for="rname">Add new reader.</label>
        <div class="form-group" style="display: flex;">
            <input style="margin-left: 5px;" type="text" name="rname" id="rname" placeholder="Enter name">
            <br>
            <input style="margin-left: 5px;" type="text" name="raddress" id="raddress" placeholder="Enter Address">
            <br>
            <input style="margin-left: 5px;" type="text" name="phone_no" id="phone_no" placeholder="Enter Phone">
            <br>
            <select type="text" name="rtype" id="rtype" placeholder="Select:">
                <option value="Student" selected>Student</option>
                <option value="Staff">Staff</option>
                <option value="Citizen">Citizen</option>
            </select>
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<br>
<div style="margin-left: 40px;">
    <form method="GET" action="{{url_for('admin.branch', id=id)}}"
        style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px; margin-right: 200px; padding: 10px;">
        <label style="font-size: 20px; color: white;" for="bid">Print branch information (name and
            location).</label>
        <div class="form-group" style="display: flex;">
            <input style="margin-left: 5px;" type="number" name="id" id="bid" placeholder="Enter BID">
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<br>
<div style="margin-left: 40px;">
    <form method="GET" action="{{url_for('admin.most_freq_borrowers_in_branch', id=id)}}"
        style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px; margin-right: 200px; padding: 10px;">
        <label style="font-size: 20px; color: white;" for="n">Get the top N most frequent borrowers in branch I</label>
        <div class="form-group" style="display: flex;">
            <input style="margin-left: 5px;" type="number" name="n" class="n-input" id="n" placeholder="Enter N">
            <br>
            <input style="margin-left: 5px;" type="number" name="id" class="i-input" id="i" placeholder="Enter I">
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<br>
<div style="margin-left: 40px;">
    <form method="GET" action="{{url_for('admin.freq_borrowers')}}"
        style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px; margin-right: 200px; padding: 10px;">
        <label style="font-size: 20px; color: white;" for="n">Get the top N most frequent borrowers in the
            library and the number of books borrowed. </label>
        <div class="form-group" style="display: flex;">
            <input style="margin-left: 5px;" type="number" name="n" class="n-input" id="n" placeholder="Enter N">
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<br>
<div style="margin-left: 40px;">
    <form method="GET" action="{{url_for('admin.most_borrowed_in_branch', id=id)}}"
        style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px; margin-right: 200px; padding: 10px;">
        <label style="font-size: 20px; color: white;" for="n">Get the N most borrowed books in branch I.</label>
        <div class="form-group" style="display: flex;">
            <input style="margin-left: 5px;" type="number" name="n" class="n-input" id="n" placeholder="Enter N">
            <br>
            <input style="margin-left: 5px;" type="number" name="id" class="i-input" id="i" placeholder="Enter I">
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<br>
<div style="margin-left: 40px;">
    <form method="GET" action="{{url_for('admin.most_borrowed')}}"
        style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px; margin-right: 200px; padding: 10px;">
        <label style="font-size: 20px; color: white;" for="n">Get the N most borrowed books in the
            library.</label>
        <div class="form-group" style="display: flex;">
            <input style="margin-left: 5px;" type="text" name="n" class="n-input" id="n" placeholder="Enter N">
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<br>
<div style="margin-left: 40px;">
    <form method="GET" action="{{url_for('admin.most_popular', year=year)}}"
        style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px; margin-right: 200px; padding: 10px;">
        <label style="font-size: 20px; color: white;" for="yr">Get the 10 most popular books of a year in the
            library.</label>
        <div class="form-group" style="display: flex;">
            <input style="margin-left: 5px;" type="number" name="year" class="yr-input" id="yr"
                placeholder="Enter year">
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<br>
<div style="margin-left: 40px;">
    <form method="GET" action="{{url_for('admin.avg_fine')}}"
        style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px; margin-right: 200px; padding: 10px;">
        <label style="font-size: 20px; color: white;" for="from_date">Get average fine paid by the borrowers by branch
            in a time period.</label>
        <div class="form-group" style="display: flex;">
            <input style="margin-left: 5px;" type="date" name="from_date" class="st-input" id="st"
                placeholder="Start Date">
            <br>
            <input style="margin-left: 5px;" type="date" name="to_date" class="end-input" id="end"
                placeholder="End Date">
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<br>
<br>
<script>
    function myCreateFunction() {
        var table = document.getElementById("myTable");
        var row = table.insertRow(0);
        var cell1 = row.insertCell(0);
        var cell2 = row.insertCell(1);
        cell1.innerHTML = '<td><input type="text" name="issuenum" id="issuenum" placeholder="Issue Num"></td>';
        cell2.innerHTML = '<td><input type="text" name="geditor" id="geditor" placeholder="Guest Editor"></td>';
    }

    function myDeleteFunction() {
        document.getElementById("myTable").deleteRow(0);
    }

    function myCreateFunction1() {
        var table = document.getElementById("myTable1");
        var row = table.insertRow(0);
        var cell1 = row.insertCell(0);
        cell1.innerHTML = '<td><input type="text" name="chair" id="chair" placeholder="Enter Chair" value="" /></td>';
    }

    function myDeleteFunction1() {
        document.getElementById("myTable1").deleteRow(0);
    }
</script>
{% endblock %}

app/templates/adminLayout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <script src="https://code.jquery.com/jquery-3.6.1.js"
        integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
{% include 'flash.html' %}

<body class="header">
    <nav class="navbar navbar-expand-md">
        <h1 class="title_library">43 2nd Ave Library</h1>
        <div class="collapse navbar-collapse" id="main-navigation">
            <ul class="navbar-nav">
                <li class="nav_item">
                    <a class="nav-link" href="{{url_for('auth.landing_page')}}">Home</a>
                </li>
                <li class="nav_item">
                    <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}{% endblock %}
</body>
</html>

app/templates/adminResults.html
{% extends "adminLayout.html" %}
{%block content%}
<h2 class="page_title">Results</h2>

<div class="container reserved_table">
    <div class="table_name">Table:</div>
    <br />
    <div class="">
        <table class="table" style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px;">
            {% if rows |length > 0 %}
            <thead>
                <tr>
                    {# generate th tags for each column to display #}
                    {# IMPORTANT use table column names as the headings, replace with space #}
                    {% for r in rows[0] %}
                    <th>{{r}}</th>
                    {% endfor %}
                </tr>
            </thead>
            {% for r in rows[1:] %}
            <tbody>
            <tr>
                {% for i in r %}
                <td>{{i}}</td>
                {% endfor %}
            </tr>
            {% endfor %}
            </tbody>
            {% else %}
            <tbody>
                <tr>
                    <td colspan="100%">No results to show</td>
                </tr>
            </tbody>
            {% endif %}
        </table>
    </div>
</div>
<br>
<br>
{% endblock %}

app/templates/contact.html
{% extends "layout.html" %}
{%block content%}
<h2 class="page_title">Contact:</h2>
<div class="container">
<h1 class="contact-details">Address: 198 West 21th Street, Suite 721 New York NY 10016
    <br>
    Phone:+ 1 235 235 5982
    <br>
    Email: 432andavelibrary@gmail.com
    <br>
    Website: 432andavelibrary.com
</h1>
</div>
{% endblock %}

app/templates/explore.html
{% extends "layout.html" %}
{%block content%}
<h2 class="page_title">Resources</h2>
<div class="container">
    <form method="GET" id="header-search-books" class="form-area" novalidate="novalidate" autocomplete="off">
        <input type="hidden" id="readerID" name="rid" value="{{rid}}">
        <div class="row">
            <div class="col-md-10">
                <div class="styled-input wide multi">
                    <div class="document-id" id="input-document-id">
                        <input type="text" name="docid" id="fn" autocomplete="off" data-placeholder-focus="false"
                            required />
                        <label>Document ID</label>
                    </div>
                    <div class="title" id="input-title">
                        <input type="text" name="title" id="ln" autocomplete="off" data-placeholder-focus="false"
                            required />
                        <label>Title</label>
                    </div>
                    <div class="pub-name" id="input-pub-name">
                        <input type="text" name="publisher_name" id="city" autocomplete="off"
                            data-placeholder-focus="false" />
                        <label>Publisher Name</label>
                    </div>
                    <div class="availability" id="select-availability">
                        <select name="available">
                            <option value="">Show all</option>
                            <option value="True">Show only Available</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-2 no-pad-left-10">
                <button type="submit" class="primary-btn serach-btn" id="submit_btn">SEARCH</button>
            </div>
        </div>
    </form>
</div>
<br>
<br>
<div class="result-table">
    <table class="table" style="background-color: rgba(0, 0, 0, 0.671); border-radius: 10px;">
        {% if rows and rows|length > 0 %}
        <thead>
            <tr>
                <th style="text-align: center;">Document ID</th>
                <th style="text-align: center;">Title</th>
                <th style="text-align: center;">Published on</th>
                <th style="text-align: center;">Publisher Name</th>
                <th style="text-align: center;">Actions</th>
            </tr>
        </thead>
        {% endif %}
        {% for r in rows[1:] %}
        <tr>
            <td style="text-align: center;">{{r[0]}}</td>
            <td>{{r[1]}}</td>
            <td>{{r[2].strftime('%Y-%m-%d')}}</td>
            <td style="text-align: center;">{{r[4]}}</td>
            <td style="display:flex;"><a href="{{url_for('reader.document', res_button=r[6], id=r[0], rid=request.args.get('rid'))}}"
                    class="btn btn-primary">View</a>
                {% if r[6] == 'True' %}
                <form
                    action="{{url_for('reader.document', id=r[0], res_button='False', rid=request.args.get('rid'))}}"
                    method="POST">
                    <button type="submit" class="btn btn-primary" style="margin-left: 10px;">Reserve</button>
                </form>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/templates/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class=flashes>
    {% for category, message in messages %}
    <div class="alert alert-{{ category or 'info' }}" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

app/templates/login.html
{% extends "secure_layout.html" %}
{% block title %}Login{% endblock %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<div class="container-fluid">
    <div class="h3 page_title">Login</div>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{render_field(form.username)}}
        {{render_field(form.password)}}
        {{form.submit(class="btn btn-primary")}}
    </form>
</div>
{% endblock %}